global using Labirint.Core;
global using Labirint.Core.Common;
global using Labirint.Core.Items.Base;
global using Labirint.Web.Common.Control;
global using Labirint.Web.Common.Drawing;
global using Labirint.Web.Components.Base;
global using Labirint.Web.Services;
global using Labirint.Web.Services.Base;
global using Microsoft.JSInterop;
global using Direction = Labirint.Core.Common.Direction;
global using Position = Labirint.Core.Common.Position;
