global using Labirint.Core;
global using Labirint.Core.Common;
global using Labirint.Core.Items;
global using LabirintBlazorApp.Common.Control;
global using LabirintBlazorApp.Common.Drawing;
global using LabirintBlazorApp.Components.Base;
global using LabirintBlazorApp.Services;
global using LabirintBlazorApp.Services.Base;
global using Microsoft.JSInterop;
